force-app/main/default/objects/HR_Object__c/HR_Object__c.object-meta.xml
<CustomObject>
    <description>This object is key in getting the HR info</description>
    <label>HR Object</label>
    <nameField>
        <label>HR Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HR Objects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HR_Object__c/fields/Base_Salary__c.field-meta.xml
<CustomField>
    <fullName>Base_Salary__c</fullName>
    <defaultValue>1000</defaultValue>
    <label>Base Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/HR_Object__c/fields/Employee_401_Match_Percent__c.field-meta.xml
<CustomField>
    <fullName>Employee_401_Match_Percent__c</fullName>
    <label>Employee 401 Match Percent</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/firstbatch_class.cls
global class firstbatch_class implements Database.Batchable<sObject>{
    global string query; 
    global Database.QueryLocator start(Database.BatchableContext BC){
        query = 'SELECT ID, Employee_401_Match_Percent__c, Base_Salary__c FROM HR_Object__c';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC , List<sobject> scope){
        List<HR_Object__c> hrobjupdate = new List<HR_Object__c>();
        for(sobject s: scope){
            HR_Object__c mem = (HR_Object__c)s;
            if(mem.Base_Salary__c > 1500){
                mem.Employee_401_Match_Percent__c = 3;
                hrobjupdate.add(mem);
            }else{
               mem.Employee_401_Match_Percent__c = 5;
                hrobjupdate.add(mem); 
            } 
        }
        
        if(hrobjupdate.size()>0){
           update hrobjupdate;
        }
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
}