force-app/main/default/objects/HR_Object__c/HR_Object__c.object-meta.xml
<CustomObject>
    <description>This object is key in getting the HR info</description>
    <label>HR Object</label>
    <nameField>
        <label>HR Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HR Objects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HR_Object__c/fields/Emp_Employer__c.field-meta.xml
<CustomField>
    <fullName>Emp_Employer__c</fullName>
    <label>Emp Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>HR Objects</relationshipLabel>
    <relationshipName>HR_Objects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HR_Object__c/fields/Employee_phone__c.field-meta.xml
<CustomField>
    <fullName>Employee_phone__c</fullName>
    <label>Employee phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/AccountTrigger_Handler.cls
public class AccountTrigger_Handler {
    
    public static void hrObjectCreation(List<Account> AccountRecords){
       List<Account> accountRecs = new List<Account>(); 
            List<HR_Object__c> insertHR = new List<HR_Object__c>(); 
            for(Account acc : AccountRecords){
                // never use a query inside a for loop - 200 Queires are allowed per transcation 
                if(acc.Rating == 'Hot'){
                    accountRecs.add(acc);
                }
            }
            
            for(Account ac : accountRecs){
                HR_Object__c  hr = new HR_Object__c (
                					Name = ac.Name +'HROBJECT',
                					Emp_Employer__c = ac.Id);
                hr.Start_Date__c  = System.today()+1;
                hr.Employee_phone__c = ac.phone_number__c;
                
                // insert hr;- limts 
                insertHR.add(hr);
            }
            
            if(insertHR.size()>0){
                insert insertHR;
            } 
    } 
    
	
}