force-app/main/default/objects/HR_Object__c/HR_Object__c.object-meta.xml
<CustomObject>
    <description>This object is key in getting the HR info</description>
    <label>HR Object</label>
    <nameField>
        <label>HR Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HR Objects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HR_Object__c/fields/Emp_Employer__c.field-meta.xml
<CustomField>
    <fullName>Emp_Employer__c</fullName>
    <label>Emp Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>HR Objects</relationshipLabel>
    <relationshipName>HR_Objects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Test_AccountTrigger.cls
@isTest
public class Test_AccountTrigger {
 	
    @isTest static void test1(){
        Account acc = New Account();
        acc.Name = 'Merrill Lynch';
        acc.Rating = 'Cold';
        acc.phone_number__c = '6099999999';
        insert acc;
        acc.Rating = 'Hot';
        update acc;
        
        HR_Object__c hr = [SELECT ID, Emp_Employer__c FROM HR_Object__c WHERE Emp_Employer__c =: acc.Id];
        system.debug(hr);
        system.assert(hr != NULL);
    }
}