force-app/main/default/objects/Sysintelli__c/Sysintelli__c.object-meta.xml
<CustomObject>
    <description>A consulting services object</description>
    <label>Sysintelli</label>
    <nameField>
        <label>Sysintelli Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Systintellis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sysintelli__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Systintellis</relationshipLabel>
    <relationshipName>Systintellis</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sysintelli__c/fields/Employee_blog__c.field-meta.xml
<CustomField>
    <fullName>Employee_blog__c</fullName>
    <label>Employee blog</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Sysintelli__c/fields/Employee_email__c.field-meta.xml
<CustomField>
    <fullName>Employee_email__c</fullName>
    <label>Employee email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/syscreation.cls
public class syscreation{
    
    public static void sysrecordcreation(List<Contact> conrecords){
        List<Sysintelli__c> sysinsert = new  List<Sysintelli__c>(); 
            for(contact cc: conrecords){
                Sysintelli__c ss = new Sysintelli__c();
                ss.Account__c = cc.AccountId;
                ss.Name = cc.LastName ;
                system.debug('sys Name is '+cc.LastName);
                ss.Employee_email__c = cc.Email;
                if(cc.Department != NULL)
                ss.Employee_blog__c  = cc.Department;
                //insert ss;
                sysinsert.add(ss);               
            }
          system.debug('list of sys records'+sysinsert);
       if(sysinsert.size()>0){
           insert sysinsert;
       }
    }

}