force-app/main/default/objects/Class_kasitech__c/Class_kasitech__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_kasitech__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>classes</relationshipLabel>
    <relationshipName>classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Class_kasitech__c/fields/Class_Amount__c.field-meta.xml
<CustomField>
    <fullName>Class_Amount__c</fullName>
    <defaultValue>10</defaultValue>
    <inlineHelpText>The value of the class</inlineHelpText>
    <label>Class Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/class_Creation.cls
public with sharing class class_Creation {


    public  void  classCreationMethod(Opportunity[] triggerValues){
         List<Class_kasitech__c> classrecordinsert = new List<Class_kasitech__c>();
        for(opportunity opp : triggerValues){
            Class_kasitech__c newclass = new Class_kasitech__c(Name= opp.Name, Account__c= opp.AccountId,
                                        Class_Amount__c =opp.Amount );
           //insert newclass;- donot do dml or soql operation inside the for loop.
           // you will hit limits
           // use collectiona
           classrecordinsert.add(newclass);
           system.debug('class record to be inserted'+ classrecordinsert);
        }

        insert classrecordinsert;
    }


}